data:
    name: 'hpatches' #hpatches
    data_dir: './data/hpatches' #./data/hpatches
    export_dir: './data/repeatibility/hpatches/sp_coco_tf_1'
    alteration: 'all'  # 'all' 'i' 'v'
    preprocessing:
        resize: [240,320]
    homography_adaptation:
        num: 0
        aggregation: 'sum'
        filter_counts: 0
        homographies:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.1
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            allow_artifacts: true
            patch_ratio: 0.5
model:
    name: 'superpoint' #superpoint
    using_bn: true
    pretrained_model: './export/mg_syn_0.pth'
    grid_size: 8
    backbone:
        backbone_type: 'VGG' #ResNetFPN
        vgg:
            channels: [64,64,64,64,128,128,128,128]
    det_head: #detector head
        feat_in_dim: 128
    des_head: #descriptor head
        feat_in_dim: 128
        feat_out_dim: 256
    batch_size: 50
    eval_batch_size: 50
    learning_rate: 0.001
    nms: 4
    topk: 1000
    det_thresh: 0.001 # 0.001
