data:
    name: 'coco'
    resize: [320,240]
    image_train_path: ['./data/mp_coco_v2/images/train2017',]
    label_train_path: ['./data/mp_coco_v2/labels/train2017/',]
    image_test_path: './data/mp_coco_v2/images/test2017/'
    label_test_path: './data/mp_coco_v2/labels/test2017/'
    augmentation:
        photometric:
            train_enable: true
            test_enable: true
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur' ]
            params:
                random_brightness: {max_abs_change: 0.2}
                random_contrast: {strength_range: [0.5, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                    nb_ellipses: 20
                motion_blur: {max_kernel_size: 3}
        homographic:
            train_enable: true
            test_enable: true
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                patch_ratio: 0.85
                max_angle: 1.5707963 #3.1415926
                allow_artifacts: true
            valid_border_margin: 3
model:
    name: 'superpoint'
    grid_size: 8
    pretrained_model: 'none'
    backbone:
        backbone_type: 'VGG' #ResNetFPN
        vgg:
            channels: [64,64,64,64,128,128,128,128]
    det_head: #detector head
        feat_in_dim: 128
    des_head: #descriptor head
        feat_in_dim: 128
        feat_out_dim: 256
    det_thresh: 0.001 # 1/65
    nms: 4
    topk: -1
solver:
    grid_size: 8
    loss:
        positive_margin: 1
        negative_margin: 0.2
        lambda_d: 0.05 #superpoint 250
        lambda_loss: 10000 #superpoint 0.0001
    epoch: 6
    freeze_backbone: true
    base_lr: 0.0001 #0.0001
    train_batch_size: 2 #2 for each gpu
    test_batch_size: 2
    sync_bn: true
    save_dir: './export/'
    model_name: 'sp'
    detection_threshold: 0.015 #0.015
    nms: 4




